// <auto-generated />
using System;
using BackEnd_FoxConn.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd_FoxConn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210910010909_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("BackEnd_FoxConn.Models.Employee", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Active")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_rule")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(104)
                        .HasColumnType("varchar(104)");

                    b.Property<int?>("RuleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("employeeId");

                    b.HasIndex("RuleId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("BackEnd_FoxConn.Models.Rule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ruleId");

                    b.Property<string>("Active")
                        .HasColumnType("longtext")
                        .HasColumnName("active");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Modified_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .HasMaxLength(54)
                        .HasColumnType("varchar(54)")
                        .HasColumnName("name");

                    b.HasKey("RuleId");

                    b.ToTable("Rule");
                });

            modelBuilder.Entity("BackEnd_FoxConn.Models.Employee", b =>
                {
                    b.HasOne("BackEnd_FoxConn.Models.Rule", "Rule")
                        .WithMany("Employee")
                        .HasForeignKey("RuleId");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("BackEnd_FoxConn.Models.Rule", b =>
                {
                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
