// <auto-generated />
using System;
using BackEnd_FoxConn.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd_FoxConn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210911201644_AjusteDados04")]
    partial class AjusteDados04
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("BackEnd_FoxConn.Models.Employees", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Active")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Modified_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(104)
                        .HasColumnType("varchar(104)");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<int?>("RulesRuleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RulesRuleId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("BackEnd_FoxConn.Models.Rules", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Active")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Modified_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(54)
                        .HasColumnType("varchar(54)");

                    b.HasKey("RuleId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("BackEnd_FoxConn.Models.Employees", b =>
                {
                    b.HasOne("BackEnd_FoxConn.Models.Rules", "Rules")
                        .WithMany("Employees")
                        .HasForeignKey("RulesRuleId");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("BackEnd_FoxConn.Models.Rules", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
